### ISSUE TITLE
Forgot password : validation check is not correct as we enter new password , it Always show First letter is capital (when enter full password still show same ) and when submit the new password it show the below message 

### ISSUE THREAD

**Issue by LtSGoel** [UdacityFrontEndScholarship/jeevan-rakht#209]
<img width="1276" alt="screen shot 2018-05-10 at 1 36 59 pm" src="https://user-images.githubusercontent.com/26035935/39859484-a81192aa-5457-11e8-92cd-b8cbafa750c6.png">

**Comment by LtSGoel** [comment]
[
<img width="1184" alt="screen shot 2018-05-10 at 1 40 39 pm" src="https://user-images.githubusercontent.com/26035935/39859542-cae140c8-5457-11e8-8348-9f394c004358.png">
](url)

**Comment by gauravsinghaec** [comment]
@LtSGoel The error message is corrected but I was not able to replicate the post error thing. Please share the steps which is causing the issue on the new password.

**Comment by LtSGoel** [comment]
this post error issue not come . since your last update... but user still unable to reset his password.Kindly look on the attached video link.
1.Password validation Still not correct
https://www.dropbox.com/s/fyql9d0zvzen1pq/reset%20password.mov?dl=0

**Comment by gauravsinghaec** [comment]
@LtSGoel Please share the password you are using, as I tried few combinations but it worked.

**Comment by LtSGoel** [comment]
The password is Shobhitgoel7017678056@

**Comment by gauravsinghaec** [comment]
@LtSGoel I was able to change the password, please check as it can be a temporary server issue.
![image](https://user-images.githubusercontent.com/15084301/39909541-eba56adc-5510-11e8-83c2-60eea5f38ef8.png)

![image](https://user-images.githubusercontent.com/15084301/39909998-d44bc866-5512-11e8-849e-b3afd5684079.png)

**Comment by gauravsinghaec** [comment]
Closing the issue as we could not replicate it.

**Comment by LtSGoel** [comment]
issue still remin the same guys
